name: Build LaTeX CV

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: CV
          path: cv.pdf
