name: Compile LaTeX CV

on:
  push:
    paths:
      - '**.tex'
      - '.github/workflows/compile-latex.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup LaTeX and Compile
      uses: xu-cheng/latex-action@v2
      with:
        root_file: cv.tex
        latexmk_use_xelatex: true
        pre_compile: |
          tlmgr update --self
          tlmgr install \
            fontspec xcolor geometry graphicx \
            babel latexmk ifthen etoolbox \
            tikz-cd pgf enumitem \
            fontawesome5 moderncv

    - name: Commit compiled PDF
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add cv.pdf
        git commit -m "Auto-compile cv.pdf from LaTeX"
        git push
