name: Build and Commit CV

on:
  push:
    paths:
      - '**.tex'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex

      - name: Commit compiled PDF
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          if [ -f cv.pdf ]; then
            git rm --cached cv.pdf || true
            git add -f cv.pdf
            git commit -m "Auto-compile and update cv.pdf from LaTeX" || echo "Nothing new to commit"
            git push || echo "Nothing to push"
          else
            echo "PDF not found, skipping commit."
          fi
