name: Compile LaTeX

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install LaTeX
        run: sudo apt-get install -y texlive-full

      - name: Compile CV
        run: pdflatex -interaction=nonstopmode cv.tex

      - name: Move PDF to docs
        run: |
          mkdir -p docs
          cp cv.pdf docs/cv.pdf
