name: Compile LaTeX CV

on:
  push:
    paths:
      - '**.tex'
      - '.github/workflows/compile-latex.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: cv.tex

    - name: Commit compiled PDF
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add cv.pdf
        git commit -m "Auto-compile cv.pdf from LaTeX"
        git push
