name: Compile LaTeX CV

on:
  push:
    paths:
      - '**.tex'
      - '.github/workflows/compile-latex.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup LaTeX and Compile
      uses: xu-cheng/latex-action@v2
      continue-on-error: true
      with:
        root_file: cv.tex
        args: -pdf -file-line-error -interaction=nonstopmode -halt-on-error -f
        latexmk_use_xelatex: true
        pre_compile: |
          tlmgr update --self
          tlmgr install \
            xcolor geometry \
            babel latexmk etoolbox \
            tikz-cd pgf enumitem \
            fontawesome5 moderncv fontspec

    - name: Force Commit Compiled PDF
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        if [ -f cv.pdf ]; then
          git rm --cached cv.pdf || true
          git add -f cv.pdf
          git commit -m "Auto-compile and update cv.pdf from LaTeX" || echo "Nothing new to commit"
          git push || echo "Nothing to push"
        else
          echo "cv.pdf not found, skipping commit."
